version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Tokyo"
    groups:
      composer-root-production-major:
        dependency-type: "production"
        patterns:
          - "*"
        exclude-patterns:
          - "laravel/framework"
        update-types:
          - "major"
      composer-root-development-major:
        dependency-type: "development"
        patterns:
          - "*"
        exclude-patterns:
          - "laravel/framework"
        update-types:
          - "major"
      composer-root-production-minor:
        dependency-type: "production"
        patterns:
          - "*"
        exclude-patterns:
          - "laravel/framework"
        update-types:
          - "minor"
      composer-root-development-minor:
        dependency-type: "development"
        patterns:
          - "*"
        exclude-patterns:
          - "laravel/framework"
        update-types:
          - "minor"
      composer-root-production-patch:
        dependency-type: "production"
        patterns:
          - "*"
        exclude-patterns:
          - "laravel/framework"
        update-types:
          - "patch"
      composer-root-development-patch:
        dependency-type: "development"
        patterns:
          - "*"
        exclude-patterns:
          - "laravel/framework"
        update-types:
          - "patch"
    labels:
      - "dependencies"
      - "composer"
      - "backend"
